#!/bin/bash
# Fix PgBouncer Configuration Issue
# The "pgbouncer" database name is reserved and causing startup failure

set -euo pipefail

info() { echo -e "\033[0;32m[INFO]\033[0m $*"; }
warn() { echo -e "\033[1;33m[WARN]\033[0m $*"; }
error() { echo -e "\033[0;31m[ERROR]\033[0m $*"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root"
    exit 1
fi

info "🔧 Fixing PgBouncer configuration issue"

PGBOUNCER_CONF_FILE="/etc/pgbouncer/pgbouncer.ini"

# Backup current config
cp "$PGBOUNCER_CONF_FILE" "${PGBOUNCER_CONF_FILE}.backup.$(date +%Y%m%d-%H%M%S)"
info "✓ Backed up current PgBouncer configuration"

# Get current role to set appropriate configuration
ROLE="primary"
if sudo -u postgres psql -Atqc "SELECT pg_is_in_recovery();" postgres 2>/dev/null | grep -q '^t'; then
    ROLE="standby"
fi

info "Detected role: $ROLE"

# Set pool mode based on role
if [[ "$ROLE" == "primary" ]]; then
    POOL_MODE="session"
    MAX_CLIENT_CONN=100
else
    POOL_MODE="transaction"
    MAX_CLIENT_CONN=150
fi

# Create corrected PgBouncer configuration
cat > "$PGBOUNCER_CONF_FILE" <<EOF
;; PgBouncer configuration for PostgreSQL HA
;; Generated by fix script - Role: $ROLE

[databases]
postgres = host=localhost port=5432 dbname=postgres
template1 = host=localhost port=5432 dbname=template1
repmgr = host=localhost port=5432 dbname=repmgr

;; NOTE: pgbouncer is a reserved database name for admin connections
;; It should NOT be listed in the [databases] section

[pgbouncer]
;; Connection settings
listen_addr = 0.0.0.0
listen_port = 6432

;; Authentication
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

;; Pool settings
pool_mode = $POOL_MODE
max_client_conn = $MAX_CLIENT_CONN
default_pool_size = 25
reserve_pool_size = 5
max_db_connections = 50

;; Timeouts
server_connect_timeout = 15
server_login_retry = 3
query_timeout = 3600
query_wait_timeout = 120
client_idle_timeout = 3600
server_idle_timeout = 600
server_lifetime = 3600

;; Logging
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1
syslog = 0
syslog_facility = daemon
log_stats = 1
stats_period = 60

;; Administration
admin_users = postgres
stats_users = postgres

;; Security
ignore_startup_parameters = extra_float_digits,search_path

;; Connection limits per user/database
max_user_connections = $((MAX_CLIENT_CONN / 2))

;; Server settings
server_reset_query = DISCARD ALL
server_reset_query_always = 0
server_check_delay = 30

;; Performance
tcp_keepalive = 1
tcp_keepcnt = 3
tcp_keepidle = 600
tcp_keepintvl = 30

;; Application name tracking
application_name_add_host = 1
EOF

chown pgbouncer:pgbouncer "$PGBOUNCER_CONF_FILE"
chmod 640 "$PGBOUNCER_CONF_FILE"
info "✓ Created corrected PgBouncer configuration"

# Test the configuration by checking syntax
info "Validating PgBouncer configuration syntax..."
if sudo -u pgbouncer /usr/sbin/pgbouncer --help >/dev/null 2>&1; then
    info "✓ PgBouncer binary is accessible"
else
    warn "✗ PgBouncer binary accessibility issue"
fi

# Check if configuration file is readable
if [[ -r "$PGBOUNCER_CONF_FILE" ]]; then
    info "✓ PgBouncer configuration file is readable"
else
    error "✗ PgBouncer configuration file is not readable"
    exit 1
fi

# Start PgBouncer
info "Starting PgBouncer..."
if systemctl start pgbouncer; then
    info "✓ PgBouncer started successfully"
    sleep 2
    
    # Check if it's running
    if systemctl is-active --quiet pgbouncer; then
        info "✓ PgBouncer is running"
        
        # Test connection
        if timeout 5 bash -c "</dev/tcp/localhost/6432" 2>/dev/null; then
            info "✅ PgBouncer is accepting connections on port 6432"
        else
            warn "✗ PgBouncer connection test failed"
        fi
    else
        error "✗ PgBouncer failed to start"
    fi
else
    error "✗ Failed to start PgBouncer"
    info "PgBouncer logs:"
    journalctl -u pgbouncer -n 10 --no-pager || true
fi

info "🎉 PgBouncer configuration fix completed!"
info "Run validation script to verify: sudo ./comprehensive_validation.sh"