#!/bin/bash
# Fix Replication Slot Issue
# Creates missing replication slot and fixes standby configuration
# Version: 1.0.0

set -euo pipefail

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
PRIMARY_IP="192.168.14.21"
STANDBY_IP="192.168.14.22"
PRIMARY_SSH_HOST="ipa-nprd-ha-pg-primary-01"
STANDBY_SSH_HOST="ipa-nprd-ha-pg-standby-01"
SSH_USER="asamy_nominations_ipa_edu_sa"
SSH_OPTIONS="-o ConnectTimeout=10 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
DB_PORT="6432"

# Logging functions
info() { printf "%b[INFO]%b %s\n" "$GREEN" "$NC" "$*"; }
warn() { printf "%b[WARN]%b %s\n" "$YELLOW" "$NC" "$*"; }
error() { printf "%b[ERROR]%b %s\n" "$RED" "$NC" "$*"; }
success() { printf "%b[SUCCESS]%b %s\n" "$GREEN" "$NC" "$*"; }
section() { printf "\n%b=== %s ===%b\n" "$BLUE" "$*" "$NC"; }

# Get credentials
if [[ -z "${PG_SUPER_PASS:-}" ]]; then
    if PG_SUPER_PASS=$(timeout 5 gcloud secrets versions access latest --secret="ipa-nprd-sec-pg-superuser-password-01" --project="ipa-nprd-svc-db-01" 2>/dev/null); then
        export PG_SUPER_PASS
    else
        export PG_SUPER_PASS='?=4-*HWWydY6rdhF34K!qD*%Q3gLc^dT'
    fi
fi

printf "%b" "$BLUE"
cat << "EOF"
╔══════════════════════════════════════════════════════╗
║         🎯 REPLICATION SLOT FIX                      ║
║    Targeted Fix for Missing repmgr_slot_1           ║
╚══════════════════════════════════════════════════════╝
EOF
printf "%b" "$NC"

info "Timestamp: $(date)"
info "Fixing missing replication slot issue"

section "🔍 Current Issue Analysis"

info "Checking existing replication slots on primary..."
existing_slots=$(timeout 10 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -c "SELECT slot_name, slot_type, active FROM pg_replication_slots;" 2>/dev/null || echo "Query failed")
info "Current slots:"
echo "$existing_slots"

section "🔧 Creating Missing Replication Slot"

info "Step 1: Creating repmgr_slot_1 on primary..."
slot_creation=$(timeout 10 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -c "
SELECT pg_create_physical_replication_slot('repmgr_slot_1');
" 2>&1)

if echo "$slot_creation" | grep -q "repmgr_slot_1"; then
    success "✅ Replication slot 'repmgr_slot_1' created successfully"
else
    if echo "$slot_creation" | grep -q "already exists"; then
        success "✅ Replication slot 'repmgr_slot_1' already exists"
    else
        error "❌ Failed to create replication slot: $slot_creation"
        exit 1
    fi
fi

section "🔄 Fixing Standby Configuration"

info "Step 2: Stopping standby to fix configuration..."
ssh $SSH_OPTIONS "$SSH_USER@$STANDBY_SSH_HOST" "sudo systemctl stop postgresql" 2>/dev/null
sleep 3

info "Step 3: Updating standby primary_conninfo to use correct user..."
ssh $SSH_OPTIONS "$SSH_USER@$STANDBY_SSH_HOST" "
    # Update postgresql.auto.conf with correct connection string
    sudo -u postgres tee /var/lib/postgresql/17/main/postgresql.auto.conf << 'EOL'
# Recovery configuration generated by pg_basebackup
primary_conninfo = 'user=postgres passfile='\''/var/lib/postgresql/.pgpass'\'' channel_binding=prefer host=192.168.14.21 port=5432 sslmode=prefer sslcompression=0 sslcertmode=allow sslsni=1 ssl_min_protocol_version=TLSv1.2 gssencmode=prefer krbsrvname=postgres gssdelegation=0 target_session_attrs=any load_balance_hosts=disable'
primary_slot_name = 'repmgr_slot_1'
EOL

    # Also update postgresql.conf if needed
    if ! sudo grep -q 'primary_conninfo' /var/lib/postgresql/17/main/postgresql.conf; then
        sudo -u postgres tee -a /var/lib/postgresql/17/main/postgresql.conf << 'EOL'

# Replication configuration
primary_conninfo = 'user=postgres host=192.168.14.21 port=5432'
primary_slot_name = 'repmgr_slot_1'
hot_standby = on
EOL
    fi
    
    echo 'Standby configuration updated'
" 2>/dev/null

success "✅ Standby configuration updated with correct primary_conninfo"

info "Step 4: Starting standby PostgreSQL..."
ssh $SSH_OPTIONS "$SSH_USER@$STANDBY_SSH_HOST" "sudo systemctl start postgresql" 2>/dev/null
sleep 10

section "🔍 Verification"

info "Step 5: Verifying replication slot is active..."
replication_wait=0
max_wait=60
replication_working=false

while [[ $replication_wait -lt $max_wait ]]; do
    # Check if slot is active
    slot_status=$(timeout 5 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -Atqc "SELECT active FROM pg_replication_slots WHERE slot_name = 'repmgr_slot_1';" 2>/dev/null || echo "")
    
    # Check replication connections
    repl_count=$(timeout 5 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -Atqc "SELECT count(*) FROM pg_stat_replication;" 2>/dev/null || echo "0")
    
    if [[ "$slot_status" == "t" && "$repl_count" -gt 0 ]]; then
        replication_working=true
        success "✅ Replication slot is active and $repl_count connection(s) established"
        break
    fi
    
    sleep 3
    ((replication_wait += 3))
    if [[ $((replication_wait % 15)) -eq 0 ]]; then
        info "Still waiting... (${replication_wait}s) - Slot active: $slot_status, Connections: $repl_count"
    fi
done

if [[ "$replication_working" == true ]]; then
    section "🎉 Success!"
    
    # Show final status
    info "📊 Final Replication Status:"
    timeout 5 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -c "
        SELECT 
            slot_name,
            slot_type,
            active,
            restart_lsn,
            confirmed_flush_lsn
        FROM pg_replication_slots 
        WHERE slot_name = 'repmgr_slot_1';
    " 2>/dev/null
    
    info "📊 Replication Connections:"
    timeout 5 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -c "
        SELECT 
            client_addr,
            application_name,
            state,
            sync_state,
            pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn) as lag_bytes
        FROM pg_stat_replication;
    " 2>/dev/null
    
    # Test data synchronization
    info "Step 6: Testing data synchronization..."
    test_table="slot_fix_test_$(date +%s)"
    test_data="slot_fix_$(date +%s%N)"
    
    if timeout 10 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -c "
        CREATE TABLE $test_table (data TEXT, created_at TIMESTAMP DEFAULT NOW());
        INSERT INTO $test_table (data) VALUES ('$test_data');
    " >/dev/null 2>&1; then
        
        sleep 5
        if timeout 5 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$STANDBY_IP" -p "$DB_PORT" -U postgres -d postgres -Atqc "SELECT data FROM $test_table WHERE data = '$test_data';" 2>/dev/null | grep -q "$test_data"; then
            success "✅ Data synchronization verified - replication is working perfectly!"
        else
            warn "⚠️ Data sync still catching up - this is normal after restart"
        fi
        
        # Cleanup
        timeout 5 env PGPASSWORD="$PG_SUPER_PASS" psql -h "$PRIMARY_IP" -p "$DB_PORT" -U postgres -d postgres -c "DROP TABLE $test_table;" >/dev/null 2>&1 || true
    fi
    
    success "🎉 REPLICATION SLOT FIX COMPLETED SUCCESSFULLY!"
    info "✅ The missing repmgr_slot_1 has been created and replication is working"
    info "✅ You can now run the failover validation script option 1 to verify"
    
else
    error "❌ Replication slot fix failed"
    info "🔧 Checking logs for remaining issues..."
    ssh $SSH_OPTIONS "$SSH_USER@$STANDBY_SSH_HOST" "sudo tail -10 /var/log/postgresql/postgresql-17-main.log" 2>/dev/null || true
fi

info "Replication slot fix script completed at $(date)"