#!/bin/bash
# Quick Manual Load Balancer Validation Commands
# Simple copy-paste commands to test PostgreSQL HA through load balancer

# Configuration - Based on your Terraform load_balancer.tf
WRITE_FQDN="pg-write.db.internal.nprd.ipa.edu.sa"
READ_FQDN="pg-read.db.internal.nprd.ipa.edu.sa"
WRITE_IP="10.xxx.xxx.xxx"  # Replace with actual IP
READ_IP="10.xxx.xxx.xxx"   # Replace with actual IP
PGBOUNCER_PORT=6432
DB_USER="postgres"
DB_NAME="postgres"

echo "🔍 PostgreSQL HA Load Balancer Quick Validation"
echo "=============================================="
echo ""

echo "📋 STEP 1: DNS Resolution"
echo "-------------------------"
echo "# Test DNS resolution:"
echo "nslookup $WRITE_FQDN"
echo "nslookup $READ_FQDN"
echo ""

echo "📋 STEP 2: Network Connectivity"
echo "-------------------------------"
echo "# Test port connectivity:"
echo "nc -zv $WRITE_FQDN $PGBOUNCER_PORT"
echo "nc -zv $READ_FQDN $PGBOUNCER_PORT"
echo ""

echo "📋 STEP 3: Database Connection Test"
echo "----------------------------------"
echo "# Connect to write endpoint (should be primary):"
echo "psql -h $WRITE_FQDN -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \"SELECT 'Write Endpoint', current_timestamp, CASE WHEN pg_is_in_recovery() THEN 'STANDBY' ELSE 'PRIMARY' END as role;\""
echo ""
echo "# Connect to read endpoint (should be standby):"
echo "psql -h $READ_FQDN -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \"SELECT 'Read Endpoint', current_timestamp, CASE WHEN pg_is_in_recovery() THEN 'STANDBY' ELSE 'PRIMARY' END as role;\""
echo ""

echo "📋 STEP 4: Replication Test"
echo "---------------------------"
echo "# 1. Insert test data on write endpoint:"
echo "psql -h $WRITE_FQDN -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \""
echo "CREATE TABLE IF NOT EXISTS lb_replication_test ("
echo "  id SERIAL PRIMARY KEY,"
echo "  message TEXT,"
echo "  created_at TIMESTAMP DEFAULT NOW()"
echo ");"
echo "INSERT INTO lb_replication_test (message) VALUES ('Load balancer test at ' || NOW());"
echo "SELECT 'Data inserted on PRIMARY via write endpoint';"
echo "SELECT id, message, created_at FROM lb_replication_test ORDER BY created_at DESC LIMIT 3;"
echo "\""
echo ""

echo "# 2. Wait 5 seconds for replication, then check on read endpoint:"
echo "sleep 5"
echo "psql -h $READ_FQDN -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \""
echo "SELECT 'Data read from STANDBY via read endpoint';"
echo "SELECT id, message, created_at FROM lb_replication_test ORDER BY created_at DESC LIMIT 3;"
echo "\""
echo ""

echo "📋 STEP 5: Health Endpoint Tests"
echo "--------------------------------"
echo "# Test backend health endpoints:"
echo "curl -s http://192.168.14.21:8001 | jq .  # Primary PostgreSQL health"
echo "curl -s http://192.168.14.22:8001 | jq .  # Standby PostgreSQL health"
echo "curl -s http://192.168.14.21:8002 | jq .  # Primary PgBouncer health"
echo "curl -s http://192.168.14.22:8002 | jq .  # Standby PgBouncer health"
echo ""

echo "📋 STEP 6: Direct Backend Tests"
echo "-------------------------------"
echo "# Test direct connections to backends:"
echo "psql -h 192.168.14.21 -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \"SELECT 'Direct Primary Connection', pg_is_in_recovery();\""
echo "psql -h 192.168.14.22 -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \"SELECT 'Direct Standby Connection', pg_is_in_recovery();\""
echo ""

echo "📋 STEP 7: Failover Simulation Test"
echo "----------------------------------"
echo "# To test failover behavior:"
echo "# 1. Stop primary PostgreSQL service:"
echo "# ssh to primary node: sudo systemctl stop postgresql"
echo "# 2. Wait 30-60 seconds for failover detection"
echo "# 3. Test write endpoint should now connect to promoted standby:"
echo "psql -h $WRITE_FQDN -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \"SELECT 'After failover', pg_is_in_recovery();\""
echo ""

echo "📋 STEP 8: Connection String Examples"
echo "------------------------------------"
echo "# Application connection strings:"
echo "Write (Primary):  postgresql://$DB_USER:password@$WRITE_FQDN:$PGBOUNCER_PORT/$DB_NAME"
echo "Read (Standby):   postgresql://$DB_USER:password@$READ_FQDN:$PGBOUNCER_PORT/$DB_NAME"
echo ""
echo "# Using IPs:"
echo "Write (IP):       postgresql://$DB_USER:password@$WRITE_IP:$PGBOUNCER_PORT/$DB_NAME"
echo "Read (IP):        postgresql://$DB_USER:password@$READ_IP:$PGBOUNCER_PORT/$DB_NAME"
echo ""

echo "📋 STEP 9: Cleanup Test Data"
echo "----------------------------"
echo "# Clean up test data:"
echo "psql -h $WRITE_FQDN -p $PGBOUNCER_PORT -U $DB_USER -d $DB_NAME -c \"DROP TABLE IF EXISTS lb_replication_test;\""
echo ""

echo "✅ VALIDATION COMPLETE"
echo "====================="
echo "Expected Results:"
echo "- Write endpoint connects to PRIMARY (pg_is_in_recovery = false)"
echo "- Read endpoint connects to STANDBY (pg_is_in_recovery = true)"
echo "- Data inserted on write endpoint appears on read endpoint"
echo "- Health endpoints return 'healthy' status"
echo "- Both FQDN and IP connections work"
echo ""